### PR TITLE
deps: support Redux v5

### PR DESCRIPTION
**Pull request by sergei-startsev**
The PR addresses #21.
https://redux.js.org/usage/migrations/migrating-rtk-2

### CODE REVIEW

**Comment by lagunovsky** [comment]
Thank you

**Comment by sergei-startsev** [comment]
@lagunovsky any chance to release a new version?

**Comment by lagunovsky** [comment]
Current code has an error https://github.com/lagunovsky/redux-react-router/actions/runs/7701523225/job/20987751381#step:4:74

**Comment by sergei-startsev** [comment]
> Current code has an error https://github.com/lagunovsky/redux-react-router/actions/runs/7701523225/job/20987751381#step:4:74

@lagunovsky check out #23

**Pull request merged**
